env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

sudo: false
language: ruby
cache: bundler

before_install:
  - gem update bundler
  
before_script:
  - bundle update

script:
  - bundle exec rspec

rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0.0
  - 2.1.10
  - 2.2.2
  - 2.3.1
  - jruby-9.0.5.0
  - ruby-head

gemfile:
  - gemfiles/rack_1.gemfile
  - gemfiles/rack_2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

  fast_finish: true

  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rack_2.gemfile

    - rvm: jruby-19mode
      gemfile: gemfiles/rack_2.gemfile

    - rvm: 2.0.0
      gemfile: gemfiles/rack_2.gemfile

    - rvm: 2.1.10
      gemfile: gemfiles/rack_2.gemfile
